### PR TITLE
remove python symlinks & omniidl superfluous files, add test, setup CI

### PR DESCRIPTION
**Pull request by nim65s**
As this breaks configuration when
`CMAKE_CURRENT_SOURCE_DIR` == `CMAKE_CURRENT_BINARY_DIR`, which is the default case in robotpkg.

If this is effectively still required for testing purposes, could I have some inputs about how to test that ?

### CODE REVIEW

**Comment by jmirabel** [comment]
I think (but I am not sure) this is required for unit-testing.
Does make test works without the symbolic links and without installing the package ?

**Comment by nim65s** [comment]
There are no tests in this package:
```
╰─>$ make test
Running tests...
/usr/bin/ctest --force-new-ctest-process 
Test project /local/users/gsaurel/humanoid-path-planner/hpp-corbaserver/build
No tests were found!!!
```

**Comment by nim65s** [comment]
Well… There is a test folder… This calls for another PR :)

**Comment by jmirabel** [comment]
They are not included in the CMakeLists.txt but they are here. I don't know whether they work.

**Comment by nim65s** [comment]
This work on 16.04 & 18.04: https://gepgitlab.laas.fr/gsaurel/hpp-corbaserver/pipelines/2869

**Comment by jmirabel** [comment]
Thanks for the cleaning !

**Pull request merged**
