### PR TITLE
Fix compilation with gcc <= 7.0

### LINKED ISSUE #137: Compilation error with gcc  5.4.0
On the master branch (for all hpp packages) I got the following compilation error on ubuntu 16.04 with gcc 5.4 :
```
[ 40%] Building CXX object src/CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o
cd /local/dev_hpp/src/hpp-corbaserver/build-rel/src && /usr/bin/c++   -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -Dhpp_corbaserver_EXPORTS -I/local/dev_hpp/src/hpp-corbaserver/build-rel -I/local/dev_hpp/src/hpp-corbaserver/build-rel/include -I/local/dev_hpp/src/hpp-corbaserver/include -I/local/dev_hpp/src/hpp-corbaserver/build-rel/src -isystem /opt/openrobots/include -isystem /local/dev_hpp/install/include -isystem /usr/include/eigen3 -isystem /usr/include/assimp  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC   -D__x86_64__ -D__linux__ -D__OSVERSION__=2 -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=0 -std=gnu++11 -o CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o -c /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc
/local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc:11:64: error: specialization of ‘template<class ServantBaseType> std::vector<hpp::corbaServer::ServantFactoryBase<ServantBaseType>*>& hpp::corbaServer::objectDowncasts()’ in different namespace [-fpermissive]
 ::hpp::corbaServer::objectDowncasts<hpp::core_impl::Distance> ()
                                                                ^
In file included from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances-fwd.hh:9:0,
                 from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.hh:8,
                 from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc:5:
/local/dev_hpp/src/hpp-corbaserver/include/hpp/corbaserver/servant-base.hh:348:58: error:   from definition of ‘template<class ServantBaseType> std::vector<hpp::corbaServer::ServantFactoryBase<ServantBaseType>*>& hpp::corbaServer::objectDowncasts()’ [-fpermissive]
     std::vector< ServantFactoryBase<ServantBaseType>* >& objectDowncasts ();
                                                          ^
src/CMakeFiles/hpp-corbaserver.dir/build.make:873 : la recette pour la cible « src/CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o » a échouée
```

After quick search it looks like a bug in gcc <= 7.0 that do not correctly implement the c++11 standard. Compilation with Clang (3.8) work correctly. 
It seems that some fix exist to avoid this (https://stackoverflow.com/questions/25594644/warning-specialization-of-template-in-different-namespace) but I did not try them.

### PR DESCRIPTION
**Pull request by nim65s**
fix #137

### CODE REVIEW

**Comment by jmirabel** [comment]
Any idea why `hppcorbaserver` is not found in the CI that fails ?

**Comment by nim65s** [comment]
This message comes from a kill, and is only a warning, saying that the *process* is not found, so that's OK we can launch the server for the test.
 
If the test fails, that's because the server segfaults :/

**Comment by nim65s** [comment]
My reproduce step (and add debug) in docker:
```
    1  cd path/py-hpp-corbaserver/
    2  echo -e 'PKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
    3  make checkout MASTER_REPOSITORY="git https://github.com/jmirabel/hpp-corbaserver.git"
    4  cd work.$HOSTNAME/hpp-corbaserver-4.10.1/
    5  git checkout devel
    6  git submodule update
    7  cd -
    8  make install
    9  cd work.$HOSTNAME/hpp-corbaserver-4.10.1/tests/
   10  ctest -VV -R robot
   11  ../src/hppcorbaserver
```

gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007f6c2c105358 in omni::orbOptions::findHandler(char const*) () from /opt/openrobots/lib/libomniORB4.so.2
#2  0x00007f6c2c1054fd in omni::orbOptions::registerHandler(omni::orbOptions::Handler&) () from /opt/openrobots/lib/libomniORB4.so.2
#3  0x00007f6c2c0bbada in omni::omni_corbaOrb_initialiser::omni_corbaOrb_initialiser() () from /opt/openrobots/lib/libomniORB4.so.2
#4  0x00007f6c2cd036fa in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffe4d7cc408, env=env@entry=0x7ffe4d7cc418) at dl-init.c:72
#5  0x00007f6c2cd0380b in call_init (env=0x7ffe4d7cc418, argv=0x7ffe4d7cc408, argc=1, l=<optimized out>) at dl-init.c:30
#6  _dl_init (main_map=0x7f6c2cf1a168, argc=1, argv=0x7ffe4d7cc408, env=0x7ffe4d7cc418) at dl-init.c:120
#7  0x00007f6c2ccf3c6a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
```

**Comment by jmirabel** [comment]
I suspect this comes from the fact that it uses both `/opt/openrobots/lib/libomniORB4.so.2` and `/usr/lib/.../libomniORB4.so.1`

**Comment by jmirabel** [comment]
The one in */usr/lib* is pulled by hpp-template-corba.

**Comment by nim65s** [comment]
This definitely looks like a robotpkg configuration issue on my side. I'll fix it.

**Comment by jmirabel** [comment]
I'll merge this to avoid having a too weird git history with some other changes.

**Comment by jmirabel** [comment]
Pushed as 55f35e3

**Pull request closed without merging**
